LOGIN = "mmalphit"
BOX = "bento/debian-13"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_check_update = false

	config.vm.define "#{LOGIN}S" do |server|
		server.vm.hostname = "#{LOGIN}S"
		server.vm.network "private_network", ip: SERVER_IP

		server.vm.provider "virtualbox" do |vb|
			vb.name = "#{LOGIN}S"
			vb.cpus = 1
			vb.memory = 1024
		end

		server.vm.provision "shell",
			path: "scripts/server.sh",
			args: [SERVER_IP]
	end

	config.vm.define "#{LOGIN}SW" do |worker|
		worker.vm.hostname = "#{LOGIN}SW"
		worker.vm.network "private_network", ip: WORKER_IP

		worker.vm.provider "virtualbox" do |vb|
			vb.name = "#{LOGIN}SW"
			vb.cpus = 1
			vb.memory = 1024
		end

		worker.vm.provision "shell",
			path: "scripts/worker.sh",
			args: [SERVER_IP, WORKER_IP]
	end
end