apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  namespace: dev
  labels:
    app: playground
spec:
  replicas: 1

  selector:
    matchLabels:
      app: playground

  template:
    metadata:
      labels:
        app: playground

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532

      containers:
        - name: playground
          image: genegrigorian/mmalphit-inception-of-things-app:v1
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: APP_NAME
              value: playground
            - name: PORT
              value: "8888"
