LOGIN = "mmalphit"
BOX = "bento/debian-13"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_check_update = false

	config.vm.define "#{LOGIN}S" do |server|
		server.vm.hostname = "#{LOGIN}S"
		server.vm.network "private_network", ip: SERVER_IP

		server.vm.provider "virtualbox" do |vb|
			vb.name = "#{LOGIN}S"
			vb.cpus = 2
			vb.memory = 2048
		end

		server.vm.provision "shell", path: "scripts/install.sh"
		server.vm.provision "shell", path: "scripts/setup.sh"
	end
end
